ref:
  as: interop-tests-fusion-access-configure-cnv-shared-storage
  from: cli
  commands: interop-tests-fusion-access-configure-cnv-shared-storage-commands.sh
  timeout: 1h0m0s
  grace_period: 5m0s
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  documentation: |-
    Configure CNV to use IBM Storage Scale shared storage for virtualization workloads.
    This step creates a shared storage class and configures CNV to use it as the default
    storage class for VMs and DataVolumes.
  env:
  - name: CNV_NAMESPACE
    documentation: The namespace for CNV
    default: "openshift-cnv"
  - name: SHARED_STORAGE_CLASS
    documentation: Storage class for shared storage between CNV and Fusion Access
    default: "ibm-spectrum-scale-cnv"
  - name: STORAGE_SCALE_NAMESPACE
    documentation: The namespace for IBM Storage Scale
    default: "ibm-spectrum-scale"
  - name: STORAGE_SCALE_CLUSTER_NAME
    documentation: The name of the IBM Storage Scale cluster
    default: "ibm-spectrum-scale"
