ref:
  as: interop-tests-configure-aws-security-groups
  from_image:
    namespace: ocp
    name: "4.12"
    tag: upi-installer
  commands: interop-tests-configure-aws-security-groups-commands.sh
  timeout: 30m0s
  best_effort: true
  credentials:
   - namespace: test-credentials
     name: fusion-access-operator
     mount_path: /var/run/secrets
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  documentation: |-
    Configure AWS security groups for Fusion Access Operator testing.
    This step is optional and will not block the test if it fails.
  env:
  - name: CUSTOM_SECURITY_GROUP_PORTS
    documentation: Comma-separated list of ports for security group configuration
    default: "12345,1191,60000-61000"
  - name: CUSTOM_SECURITY_GROUP_PROTOCOLS
    documentation: Comma-separated list of protocols (tcp, udp, icmp)
    default: "tcp"
  - name: CUSTOM_SECURITY_GROUP_SOURCES
    documentation: Comma-separated list of source security groups or CIDR blocks (defaults to worker security group)
    default: ""
